# Generated by Django 5.2.3 on 2026-05-16 13:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseSociale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage (du moins cher au plus cher)")),
            ],
            options={
                'verbose_name': 'Classe sociale',
                'verbose_name_plural': 'Classes sociales',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code Nirgescom (ex: 100)', max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Famille',
                'verbose_name_plural': 'Familles',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ImportCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('nirgescom', 'Export Nirgescom (XLS)'), ('odoo', 'Export Odoo (CSV)'), ('manuel', 'Saisie manuelle')], default='nirgescom', max_length=20)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('succes', 'Succès'), ('erreur', 'Erreur'), ('partiel', 'Succès partiel')], default='en_cours', max_length=20)),
                ('nb_articles_total', models.IntegerField(default=0)),
                ('nb_articles_crees', models.IntegerField(default=0)),
                ('nb_articles_mis_a_jour', models.IntegerField(default=0)),
                ('nb_articles_ignores', models.IntegerField(default=0)),
                ('erreurs', models.TextField(blank=True, help_text='Log des erreurs ligne par ligne')),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('importe_par', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Import catalogue',
                'verbose_name_plural': 'Imports catalogue',
                'ordering': ['-date_import'],
            },
        ),
        migrations.CreateModel(
            name='PointDeVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('ville', models.CharField(default='Yaoundé', max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Point de vente',
                'verbose_name_plural': 'Points de vente',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Problematique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, help_text="Emoji ou code icône affiché dans l'interface vendeur", max_length=10)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Problématique beauté',
                'verbose_name_plural': 'Problématiques beauté',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='ConseilEffectue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_generique', models.CharField(blank=True, help_text='Identifiant du compte utilisé (générique ou nominatif)', max_length=100)),
                ('date_conseil', models.DateTimeField(auto_now_add=True)),
                ('synchronise', models.BooleanField(default=True, help_text='False = créé hors ligne, en attente de synchronisation')),
                ('classe_sociale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conseils', to='conseil_vente.classesociale')),
                ('point_de_vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conseils', to='conseil_vente.pointdevente')),
                ('problematique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conseils', to='conseil_vente.problematique')),
            ],
            options={
                'verbose_name': 'Conseil effectué',
                'verbose_name_plural': 'Conseils effectués',
                'ordering': ['-date_conseil'],
            },
        ),
        migrations.CreateModel(
            name='SousFamille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code Nirgescom (ex: 100101)', max_length=10, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('actif', models.BooleanField(default=True)),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_familles', to='conseil_vente.famille')),
            ],
            options={
                'verbose_name': 'Sous-famille',
                'verbose_name_plural': 'Sous-familles',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_nirgescom', models.CharField(db_index=True, help_text='Code article Nirgescom (ex: 1003150013-)', max_length=30, unique=True)),
                ('designation', models.CharField(max_length=255)),
                ('prix_detail', models.DecimalField(decimal_places=0, help_text='Prix de vente en FCFA', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'achat — confidentiel", max_digits=12, null=True)),
                ('prix_revient', models.DecimalField(blank=True, decimal_places=2, help_text='Prix de revient — confidentiel', max_digits=12, null=True)),
                ('image_nom', models.CharField(blank=True, help_text='Nom du fichier image sans extension (ex: DSC_8469)', max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('date_import', models.DateTimeField(auto_now=True)),
                ('sous_famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='conseil_vente.sousfamille')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='ConseilArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dans_conseils', to='conseil_vente.article')),
                ('conseil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='conseil_vente.conseileffectue')),
            ],
            options={
                'verbose_name': 'Article conseillé',
                'verbose_name_plural': 'Articles conseillés',
                'unique_together': {('conseil', 'article')},
            },
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage du produit (0 = premier affiché)")),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='conseil_vente.article')),
                ('classe_sociale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='conseil_vente.classesociale')),
                ('problematique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='conseil_vente.problematique')),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
                'ordering': ['problematique', 'classe_sociale', 'ordre'],
                'unique_together': {('problematique', 'classe_sociale', 'article')},
            },
        ),
    ]
