# Generated by Django 5.2.3 on 2026-05-17 02:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def creer_affectations_initiales(apps, schema_editor):
    AffectationPDV = apps.get_model('conseil_vente', 'AffectationPDV')
    PointDeVente = apps.get_model('conseil_vente', 'PointDeVente')

    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)

    mapping = {
        'vendeur_mokolo': 1,
        'vendeur_siege': 2,
    }
    aujourd_hui = django.utils.timezone.localdate()

    for username, pdv_id in mapping.items():
        user = User.objects.filter(username=username).first()
        pdv = PointDeVente.objects.filter(pk=pdv_id).first()

        if user is None or pdv is None:
            continue

        if AffectationPDV.objects.filter(
            user_id=user.pk,
            actif=True,
            date_fin__isnull=True,
        ).exists():
            continue

        AffectationPDV.objects.create(
            user_id=user.pk,
            point_de_vente_id=pdv.pk,
            date_debut=aujourd_hui,
            actif=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('conseil_vente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationPDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(default=django.utils.timezone.localdate)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('point_de_vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_utilisateurs', to='conseil_vente.pointdevente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_pdv', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affectation point de vente',
                'verbose_name_plural': 'Affectations points de vente',
                'ordering': ['-actif', '-date_debut', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('user',), name='unique_affectation_active_par_utilisateur')],
            },
        ),
        migrations.RunPython(creer_affectations_initiales, migrations.RunPython.noop),
    ]
