# Generated by Django 5.2.3 on 2026-05-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conseil_vente', '0002_affectationpdv'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_upload',
            field=models.ImageField(blank=True, help_text="Image téléversée depuis l'administration", null=True, upload_to='articles/'),
        ),
    ]
